-- Optional Cortex Search configuration for entity-style lookups from the local search agent.
-- Run after snowflake/setup.sql.

USE ROLE CMS_DEVELOPER_ROLE;
USE WAREHOUSE CMS_WH;
USE DATABASE CMS_DB;
USE SCHEMA CMS_DB.ANALYTICS;

CREATE OR REPLACE CORTEX SEARCH SERVICE CMS_PROVIDER_SEARCH
  ON PROVIDER_NAME
  ATTRIBUTES PROVIDER_ID, PROVIDER_TYPE, SPECIALTY, CITY, STATE
  WAREHOUSE = CMS_WH
  TARGET_LAG = '1 hour'
AS (
  SELECT PROVIDER_ID, PROVIDER_NAME, PROVIDER_TYPE, SPECIALTY, CITY, STATE
  FROM CMS_DB.ANALYTICS.PROVIDERS
);
